### ISSUE TITLE
Upgrade postcss-nesting dependency version for Node 17+ support

### ISSUE THREAD

**Issue by onlime** [nuxt-modules/tailwindcss#394]
### Version

@nuxtjs/tailwindcss: v4.2.1
nuxt: v2.15.8
node: v17.0.1

### Steps to reproduce

Try to install `@nuxtjs/tailwindcss` in a plain nuxt project:

```bash
$ yarn add @nuxtjs/tailwindcss
yarn add v1.22.17
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
error postcss-nesting@8.0.1: The engine "node" is incompatible with this module. Expected version "12 - 16". Got "17.0.1"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

### What is Expected?

`@nuxtjs/tailwindcss` should install latest `postcss-nesting@9.0.1` version where this issue has been fixed. In both [postcss-nesting](https://github.com/csstools/postcss-nesting) 8.0.1 and 9.0.0, Node version was limited to 12-16, not supporting latest Node 17+ versions. This has been fixed in https://github.com/csstools/postcss-nesting/issues/87 **postcss-nesting 9.0.1**

suggested change in `package.json`:

```diff
-    "postcss-nesting": "^8.0.1",
+    "postcss-nesting": "^9.0.1",
```

**Comment by thevuong** [comment]
Tôi thấy rằng `"postcss-nesting": "^9.0.1"` đã không được xuất bản.

**Comment by onlime** [comment]
> I found that `"postcss-nesting": "^9.0.1"` was not published.

ok, I have asked the maintainer on https://github.com/csstools/postcss-nesting/issues/87#issuecomment-969996939 to publish it. Let's hope this is fixed soon.

**Comment by amurf** [comment]
This is still happening and a new version of `postcss-nesting` has been released `10.0.2`

PR open here as well https://github.com/nuxt-community/tailwindcss-module/pull/397

**Comment by onlime** [comment]
> PR open here as well #397

@amurf Is this going to be merge and make it into a release soon? any blockers?

**Comment by onlime** [comment]
Happy New Year! Can #397 be merged anytime soon?

**Comment by aprilahijriyan** [comment]
any updates here?

**Comment by constancehermit** [comment]
I was encountering this issue, and saw that #397 got closed without merging. 

So I bumped @nuxt/tailwindcss to v5.0.0-4 
& saw that postcss-nesting got updated to 10.1.2 

I guess the the plain nuxt installation should choose a more recent @nuxt/tailwindcss version?

**Comment by Christopotamus** [comment]
> I was encountering this issue, and saw that #397 got closed without merging.
> 
> So I bumped @nuxt/tailwindcss to v5.0.0-4 & saw that postcss-nesting got updated to 10.1.2 (edit: where the issue is fixed)
> 
> I guess the the plain nuxt installation should choose a more recent @nuxt/tailwindcss version?

This fixes it for me as well.

I'm using yarn, so a simple `yarn add @nuxtjs/tailwindcss` was enough to get it working for me.

**Comment by antoinne85** [comment]
It appears that this dependency update has already been completed. Is this issue ready to close?
