### ISSUE TITLE
tailwind viewer is not working on nuxt2

### ISSUE THREAD

**Issue by asc0910** [nuxt-modules/tailwindcss#657]
### Version
@nuxtjs/tailwindcss: 6.5.5
nuxt: 2.15.7

### Steps to reproduce
navigate to localhost:3000/_tailwind/

### What is Expected?
shows view properly

### What is actually happening?
It shows an error Cannot read properties of undefined: (reading url)

I think this is an error here:
https://github.com/nuxt-modules/tailwindcss/blob/main/src/module.ts#L273
```js
if (isNuxt2()) { nuxt.options.serverMiddleware.push({ route, handler: viewerDevMiddleware }) }
```

This should be changed to 
```js
if (isNuxt2()) { nuxt.options.serverMiddleware.push({ route, handler: (req, res, next) => viewerDevMiddleware(new H3Event(req, res)) }); }
```

**Comment by Atinux** [comment]
Could you try with `v6.6.6` @asc0910 ?

**Comment by asc0910** [comment]
@Atinux  Thank you. I've already installed the new version.

**Comment by asc0910** [comment]
No, the error is fixed. Thank you for the quick merge

**Comment by valh1996** [comment]
Hi @Atinux,
I have this warning using Nuxt Bridge:
```
 WARN  [h3] Implicit event handler conversion is deprecated. Use eventHandler() or fromNodeMiddleware() to define event handlers.                                                14:28:09
     Route: /_tailwind 
     Handler: (req, res) => viewerDevMiddleware(new H3Event(req, res))
```
Is it related please?

**Comment by homerjam** [comment]
This is still an issue for me

"nuxt": "^2.17.1"
"@nuxtjs/tailwindcss": "^6.8.0",

**Comment by valh1996** [comment]
@Atinux Any news on this please?

The error:
<img width="921" alt="CleanShot 2023-10-09 at 12 02 31@2x" src="https://github.com/nuxt-modules/tailwindcss/assets/20521112/e09817f0-1104-4b50-bcf1-1558ceaae6e3">

Config:
```
- Operating System: Darwin
- Node Version:     v16.18.0
- Nuxt Version:     2.17.2-28271541.6132947
- CLI Version:      3.8.4
- Nitro Version:    2.6.3
- Package Manager:  npm@8.19.2
- Builder:          webpack
- User Config:      bridge, head, css, plugins, components, buildModules, modules, build, axios, runtimeConfig, auth, toast, i18n, router, serverHandlers, devServerHandlers, devServer, typescript, nitro
- Runtime Modules:  @nuxtjs/axios@5.13.6, @nuxtjs/auth-next@5.0.0-1642083611.1785b0f, @nuxtjs/toast@3.3.1, @nuxtjs/i18n@7.3.1, portal-vue/nuxt, @nuxtjs/tailwindcss@6.8.0
- Build Modules:    (), @nuxt/postcss8@1.1.3, @nuxt/bridge@3.0.0-rc.1-28271265.8fa71e1
```

**Comment by basemkhirat** [comment]
Any solution? I am using `6.9.4` and have the same error.

**Comment by Jones-S** [comment]
I am running `"nuxt": "^2.17.1",` with `"@nuxtjs/tailwindcss": "^6.12.0",` with node 18 and I can't get the `_tailwind` viewer get to run.
Did anyone find a solution to use nuxt2 together with a newer @nuxtjs/tailwindcss installation than v4?

**Comment by ineshbose** [comment]
> I am running `"nuxt": "^2.17.1",` with `"@nuxtjs/tailwindcss": "^6.12.0",` with node 18 and I can't get the `_tailwind` viewer get to run.
> 
> Did anyone find a solution to use nuxt2 together with a newer @nuxtjs/tailwindcss installation than v4?
> 
> 

Hi, all issues should be fixed - what error are you getting? (blank screen with console messages possibly?)

**Comment by Jones-S** [comment]
Actually I don't get any error. It is just nuxt showing me a 404 because it can't find the page with that slug.
I did workaround by starting the tailwind viewer on port 3002 in another task. At least I can keep on working now...
